- name: Remove swapfile from /etc/fstab
  mount:
    name: swap
    fstype: swap
    state: absent

- name: Disable swap
  shell: swapoff -a
  when: ansible_swaptotal_mb > 0


- name: Instal pre packages
  apt:
    name: apt-transport-https

- name: Add kubernetes gpg key
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present

- name: Add kubernetes repositorie
  apt_repository:
    repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
    state: present


- name: Installing kubeadm, kubelet, kubectl, and shared packages stable
  apt:
    name: ['kubelet', 'kubeadm', 'kubectl', 'unzip', 'tar', 'btrfs-tools', 'libseccomp2', 'socat', 'util-linux', 'curl', 'nfs-common', 'portmap', 'ceph-common', 'python-apt']
    update_cache: yes


- name: Enable & start kubelet
  systemd:
    name: kubelet
    state: restarted
    enabled: yes
    daemon_reload: yes
